% This test file was generated by Copilot. Validate generated output before use.
classdef TestNyquistCode < matlab.unittest.TestCase
    % TestNyquistCode Unit tests for the NyquistCode script.
    %
    % These tests exercise the public effects of running the script:
    % - Variables created on the workspace with expected sizes and types
    % - Downsampling function handle produces consistent outputs
    % - Reconstruction arrays align with original time vector
    %
    % The script is expected to create variables in the base workspace when run.

    methods(Test)
        function testScriptCreatesVariables(testCase)
            % Verify that running the script creates key variables with expected types/sizes.

            % Run the script in a fresh function workspace to avoid contaminating base.
            run('NyquistCode');

            % Check existence and basic properties of important variables
            testCase.verifyTrue(exist('fs_analog','var') == 1);
            testCase.verifyGreaterThan(fs_analog, 0);

            testCase.verifyTrue(exist('t','var') == 1);
            testCase.verifyClass(t, 'double');
            testCase.verifyGreaterThanOrEqual(numel(t), 2);

            testCase.verifyTrue(exist('signal','var') == 1);
            testCase.verifyClass(signal, 'double');
            testCase.verifyEqual(size(signal), size(t));

            % Sampling rates defined in the script
            testCase.verifyTrue(exist('fs_high','var') == 1);
            testCase.verifyTrue(exist('fs_low','var') == 1);
            testCase.verifyTrue(exist('fs_undersamp','var') == 1);

            % downsample_and_reconstruct handle should exist and be a function handle
            testCase.verifyTrue(exist('downsample_and_reconstruct','var') == 1);
            testCase.verifyClass(downsample_and_reconstruct, 'function_handle');
        end

        function testDownsampleStructContents(testCase)
            % Verify the downsample_and_reconstruct handle returns a struct with expected fields.

            run('NyquistCode');

            % Call with a representative sampling rate
            fs_test = 4000;
            d = downsample_and_reconstruct(fs_test);

            % Verify returned struct fields
            testCase.verifyTrue(isstruct(d));
            testCase.verifyTrue(isfield(d, 'fs'));
            testCase.verifyTrue(isfield(d, 't_samp'));
            testCase.verifyTrue(isfield(d, 'x_samp'));

            % Check fs matches requested sampling rate
            testCase.verifyEqual(d.fs, fs_test);

            % t_samp should be a non-empty increasing vector within original time span
            testCase.verifyGreaterThan(numel(d.t_samp), 1);
            testCase.verifyGreaterThanOrEqual(d.t_samp(1), 0);
            testCase.verifyLessThanOrEqual(d.t_samp(end), max(t));
            testCase.verifyTrue(all(diff(d.t_samp) > 0));

            % x_samp should match t_samp length
            testCase.verifyEqual(numel(d.x_samp), numel(d.t_samp));
        end

        function testReconstructionAlignment(testCase)
            % Verify that reconstructions have the same length as the original high-res time vector.

            run('NyquistCode');

            % Ensure reconstructions exist
            testCase.verifyTrue(exist('recon_high','var') == 1);
            testCase.verifyTrue(exist('recon_low','var') == 1);
            testCase.verifyTrue(exist('recon_under','var') == 1);

            % recon_* should be same size as t and signal
            testCase.verifyEqual(size(recon_high), size(t));
            testCase.verifyEqual(size(recon_low), size(t));
            testCase.verifyEqual(size(recon_under), size(t));
        end

        function testSpectrumComputation(testCase)
            % Verify that the script computes X_orig and frequency vector f consistent with nfft and fs_analog.

            run('NyquistCode');

            testCase.verifyTrue(exist('X_orig','var') == 1);
            testCase.verifyTrue(exist('f','var') == 1);
            testCase.verifyTrue(exist('nfft','var') == 1);

            % X_orig length should be nfft
            testCase.verifyEqual(numel(X_orig), nfft);

            % Frequency vector should be same length and span 0..fs_analog (exclusive)
            testCase.verifyEqual(numel(f), nfft);
            testCase.verifyEqual(f(1), 0);
            testCase.verifyEqual(f(end), (nfft-1)/nfft*fs_analog);
        end

        function testPlotsDoNotError(testCase)
            % Running the script should be able to create figures without throwing errors.
            % This test attempts to run the script and then close created figures.

            % Capture current figures
            figsBefore = findall(0,'Type','figure');

            run('NyquistCode');

            figsAfter = findall(0,'Type','figure');
            newFigs = setdiff(figsAfter, figsBefore);

            % There should be at least two new figures as the script creates figures
            testCase.verifyGreaterThanOrEqual(numel(newFigs), 1);

            % Close newly created figures to clean up
            close(newFigs);
        end
    end
end